# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-c5-ayDH3J-Ka_vuHAXlUqhhvsgpOG9
"""

import streamlit as st
import pandas as pd
import numpy as np

# 1. 頁面基本設定 (寬螢幕模式)
st.set_page_config(page_title="Smart Money Tracker", layout="wide")

# 2. 模擬數據生成 (實務上這裡會換成您的 SEC API 或資料庫連線)
@st.cache_data
def load_mock_13f_data(ticker):
    data = {
        "機構名稱": ["Bridgewater", "Renaissance", "Citadel", "Vanguard", "BlackRock"],
        "變動類型": ["新進 (New)", "增持 (Add)", "減持 (Reduce)", "增持 (Add)", "清倉 (Exit)"],
        "股數變動": [150000, 320000, -50000, 1200000, -800000],
        "季末市值(萬美元)": [2250, 4800, 750, 18000, 0]
    }
    return pd.DataFrame(data)

@st.cache_data
def load_mock_form4_data(ticker):
    data = {
        "申報日": ["2026-08-15", "2026-08-10", "2026-08-02"],
        "內部人姓名": ["Tim Cook", "Luca Maestri", "Arthur Levinson"],
        "職稱": ["CEO", "CFO", "Director"],
        "交易代碼": ["S (賣出)", "P (買進)", "P (買進)"],
        "成交均價": [175.5, 168.2, 165.0],
        "交易股數": [-100000, 25000, 10000]
    }
    return pd.DataFrame(data)

# 3. 左側邊欄設計 (Sidebar)
st.sidebar.header("⚙️ 參數設定")
ticker = st.sidebar.text_input("輸入股票代號 (Ticker)", value="AAPL").upper()
lookback = st.sidebar.slider("回溯期間 (月)", min_value=1, max_value=12, value=3)
st.sidebar.markdown("---")
st.sidebar.write("💡 *資料來源：SEC EDGAR 13F/Form 4*")

# 4. 主頁面標題與 KPI 看板
st.title(f"📈 {ticker} 籌碼與風控分析儀表板")

col1, col2, col3 = st.columns(3)
with col1:
    st.metric(label="13F 機構淨買入股數", value="+ 820,000", delta="較上季增長 15%")
with col2:
    st.metric(label="Form 4 內部人買賣比", value="0.35", delta="-0.1 (賣壓偏重)", delta_color="inverse")
with col3:
    st.metric(label="綜合訊號強度", value="中性偏多", delta="動量支撐")

st.markdown("---")

# 5. 標籤頁面設計 (Tabs)
tab1, tab2, tab3 = st.tabs(["🏛️ 13F 機構動向", "👔 Form 4 內部人", "🛡️ 投資組合與風控"])

with tab1:
    st.subheader("大型機構季末持倉變動")
    df_13f = load_mock_13f_data(ticker)

    # 畫個簡單的圖表
    chart_data = df_13f.set_index("機構名稱")["股數變動"]
    st.bar_chart(chart_data)

    # 顯示數據表
    st.dataframe(df_13f, use_container_width=True)

with tab2:
    st.subheader("高管與董事近期交易紀錄 (Form 4)")
    df_form4 = load_mock_form4_data(ticker)

    # 標示買賣顏色
    def color_code(val):
        color = 'red' if 'S' in val else 'green'
        return f'color: {color}'

    st.dataframe(df_form4.style.map(color_code, subset=['交易代碼']), use_container_width=True)

with tab3:
    st.subheader("風險指標評估 (Risk Metrics)")
    st.write("結合機構集中度與歷史波動度，計算基礎風險參數：")

    col_risk1, col_risk2 = st.columns(2)
    with col_risk1:
        st.info("**持股集中度 (HHI)**: 0.12 (分散)")
        st.info("**95% 歷史 VaR (單日)**: -2.4%")
    with col_risk2:
        st.warning("**風險提示**：前五大機構佔據 45% 流通股，若遭遇集體拋售可能引發流動性踩踏。")